site_name: Dendê - Documentação
site_url: https://code-silva.github.io/Dende/

theme:
    name: material
    logo: img/logo_projeto_mercado.png
    favicon: img/logo_projeto_mercado.png
    features:
        - toc.autohide
        - navigation.instant
        - navigation.tracking
        - search.suggest
        - search.highlight

markdown_extensions:
    - admonition
    - pymdownx.details

    # ---------------------------------------------

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2025 Projeto Anonna. Todos os direitos reservados.

extra:
    generator: false # Remove a frase "Made with Material for MkDocs"

nav: # Estrutura de navegação principal (menu lateral)
    - Home: index.md
    # 2. Página de Arquitetura (Inserir este bloco)
    - Arquitetura:
        - Diagrama da Arquitetura: Arquitetura/arq.md
    - Banco de Dados: database/database.md
    - Telas do Projeto:
        - Tela Inicial: telas/tela-inicial.md
        - Tela de Busca: telas/tela-de-busca.md
        - Perfil: telas/perfil.md
    - API: API/api.md
    - Requisitos:
        - Requisitos Funcionais: requisitos/requisitos_funcionais.md
        - Requisitos Não Funcionais: requisitos/requisitos_nao_funcionais.md
        - Backlog de Produto: requisitos/Backlog.md
        - DoR e DoD: requisitos/Dor_Dod.md
    - Sprints:
        - Sprints e Reuniões: sprints/sprint.md