# Generated by Django 6.0.2 on 2026-08-06 23:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083, unique=True)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='ParentSupermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Supermercado Matriz',
                'verbose_name_plural': 'Supermercados Matrizes',
            },
        ),
        migrations.CreateModel(
            name='BranchSupermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(default='', max_length=255)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='DF', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('parent_supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='app.parentsupermarket')),
            ],
            options={
                'verbose_name': 'Supemercado Filial',
                'verbose_name_plural': 'Supemercado Filiais',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('measurement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('measurement_unit', models.CharField(choices=[('KG', 'KG'), ('G', 'G'), ('L', 'L'), ('ML', 'ML'), ('UN', 'UN')], default='UN', max_length=50)),
                ('european_article_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='BranchProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='app.branchsupermarket')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_links', to='app.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_offers', to='app.product')),
            ],
            options={
                'verbose_name': 'Produto Ofertado',
                'verbose_name_plural': 'Produtos Ofertados',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WP', 'Wrong Price'), ('NP', 'Nonexistent Product'), ('EO', 'Expired Offer'), ('O', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('P', 'Pending'), ('I', 'Groundless')], max_length=20)),
                ('device_id', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.offer')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.AddConstraint(
            model_name='branchsupermarket',
            constraint=models.UniqueConstraint(fields=('coordinates', 'parent_supermarket'), name='unique_coordinates_parent_supermarket'),
        ),
    ]
