# Generated by Django 6.0.2 on 2026-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchsupermarket',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branchsupermarket',
            name='complement',
        ),
        migrations.AlterField(
            model_name='branchsupermarket',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
