# Generated by Django 6.0.2 on 2026-08-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_trgm_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branchproductoffer',
            constraint=models.UniqueConstraint(fields=('product', 'branch_supermarket', 'offer'), name='unique_product_branch_offer'),
        ),
    ]
